package com.lib.equipment.manager.model;

public class CourseMatrial {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_matrial.id
     *
     * @mbg.generated Thu Sep 19 20:02:21 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_matrial.course_id
     *
     * @mbg.generated Thu Sep 19 20:02:21 CST 2019
     */
    private Integer courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_matrial.material_id
     *
     * @mbg.generated Thu Sep 19 20:02:21 CST 2019
     */
    private Long materialId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_matrial.per
     *
     * @mbg.generated Thu Sep 19 20:02:21 CST 2019
     */
    private Integer per;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_matrial.id
     *
     * @return the value of course_matrial.id
     *
     * @mbg.generated Thu Sep 19 20:02:21 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_matrial.id
     *
     * @param id the value for course_matrial.id
     *
     * @mbg.generated Thu Sep 19 20:02:21 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_matrial.course_id
     *
     * @return the value of course_matrial.course_id
     *
     * @mbg.generated Thu Sep 19 20:02:21 CST 2019
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_matrial.course_id
     *
     * @param courseId the value for course_matrial.course_id
     *
     * @mbg.generated Thu Sep 19 20:02:21 CST 2019
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_matrial.material_id
     *
     * @return the value of course_matrial.material_id
     *
     * @mbg.generated Thu Sep 19 20:02:21 CST 2019
     */
    public Long getMaterialId() {
        return materialId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_matrial.material_id
     *
     * @param materialId the value for course_matrial.material_id
     *
     * @mbg.generated Thu Sep 19 20:02:21 CST 2019
     */
    public void setMaterialId(Long materialId) {
        this.materialId = materialId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_matrial.per
     *
     * @return the value of course_matrial.per
     *
     * @mbg.generated Thu Sep 19 20:02:21 CST 2019
     */
    public Integer getPer() {
        return per;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_matrial.per
     *
     * @param per the value for course_matrial.per
     *
     * @mbg.generated Thu Sep 19 20:02:21 CST 2019
     */
    public void setPer(Integer per) {
        this.per = per;
    }
}