package com.lib.equipment.manager.model;

import java.util.Date;

public class CoursePlan {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_plan.id
     *
     * @mbg.generated Sat Sep 07 09:15:14 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_plan.course_id
     *
     * @mbg.generated Sat Sep 07 09:15:14 CST 2019
     */
    private Integer courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_plan.num
     *
     * @mbg.generated Sat Sep 07 09:15:14 CST 2019
     */
    private Integer num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_plan.school_time
     *
     * @mbg.generated Sat Sep 07 09:15:14 CST 2019
     */
    private Date schoolTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_plan.id
     *
     * @return the value of course_plan.id
     *
     * @mbg.generated Sat Sep 07 09:15:14 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_plan.id
     *
     * @param id the value for course_plan.id
     *
     * @mbg.generated Sat Sep 07 09:15:14 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_plan.course_id
     *
     * @return the value of course_plan.course_id
     *
     * @mbg.generated Sat Sep 07 09:15:14 CST 2019
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_plan.course_id
     *
     * @param courseId the value for course_plan.course_id
     *
     * @mbg.generated Sat Sep 07 09:15:14 CST 2019
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_plan.num
     *
     * @return the value of course_plan.num
     *
     * @mbg.generated Sat Sep 07 09:15:14 CST 2019
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_plan.num
     *
     * @param num the value for course_plan.num
     *
     * @mbg.generated Sat Sep 07 09:15:14 CST 2019
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_plan.school_time
     *
     * @return the value of course_plan.school_time
     *
     * @mbg.generated Sat Sep 07 09:15:14 CST 2019
     */
    public Date getSchoolTime() {
        return schoolTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_plan.school_time
     *
     * @param schoolTime the value for course_plan.school_time
     *
     * @mbg.generated Sat Sep 07 09:15:14 CST 2019
     */
    public void setSchoolTime(Date schoolTime) {
        this.schoolTime = schoolTime;
    }
}