package com.lib.equipment.manager.model;

import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;

public class Course {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.id
     *
     * @mbg.generated Thu Sep 19 20:02:21 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.course_name
     *
     * @mbg.generated Thu Sep 19 20:02:21 CST 2019
     */
    @NotBlank(message = "不能为空")
    private String courseName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.course_no
     *
     * @mbg.generated Thu Sep 19 20:02:21 CST 2019
     */
    @NotBlank(message = "不能为空")
    private String courseNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.id
     *
     * @return the value of course.id
     *
     * @mbg.generated Thu Sep 19 20:02:21 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.id
     *
     * @param id the value for course.id
     *
     * @mbg.generated Thu Sep 19 20:02:21 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    @Override
    public String toString() {
        return "Course{" +
                "id=" + id +
                ", courseName='" + courseName + '\'' +
                ", courseNo='" + courseNo + '\'' +
                '}';
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.course_name
     *
     * @return the value of course.course_name
     *
     * @mbg.generated Thu Sep 19 20:02:21 CST 2019
     */
    public String getCourseName() {
        return courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.course_name
     *
     * @param courseName the value for course.course_name
     *
     * @mbg.generated Thu Sep 19 20:02:21 CST 2019
     */
    public void setCourseName(String courseName) {
        this.courseName = courseName == null ? null : courseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.course_no
     *
     * @return the value of course.course_no
     *
     * @mbg.generated Thu Sep 19 20:02:21 CST 2019
     */
    public String getCourseNo() {
        return courseNo;
    }

    public Course() {
    }

    public Course( String courseName, String courseNo) {
        this.courseName = courseName;
        this.courseNo = courseNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.course_no
     *
     * @param courseNo the value for course.course_no
     *
     * @mbg.generated Thu Sep 19 20:02:21 CST 2019
     */
    public void setCourseNo(String courseNo) {
        this.courseNo = courseNo == null ? null : courseNo.trim();
    }
}