package com.lib.equipment.manager.model;

public class CoursePlan {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_plan.id
     *
     * @mbg.generated Wed Sep 25 22:13:22 GMT+08:00 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_plan.course_id
     *
     * @mbg.generated Wed Sep 25 22:13:22 GMT+08:00 2019
     */
    private Integer courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_plan.num
     *
     * @mbg.generated Wed Sep 25 22:13:22 GMT+08:00 2019
     */
    private Integer num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_plan.school_time
     *
     * @mbg.generated Wed Sep 25 22:13:22 GMT+08:00 2019
     */
    private String schoolTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_plan.mark
     *
     * @mbg.generated Wed Sep 25 22:13:22 GMT+08:00 2019
     */
    private String mark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_plan.id
     *
     * @return the value of course_plan.id
     *
     * @mbg.generated Wed Sep 25 22:13:22 GMT+08:00 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_plan.id
     *
     * @param id the value for course_plan.id
     *
     * @mbg.generated Wed Sep 25 22:13:22 GMT+08:00 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_plan.course_id
     *
     * @return the value of course_plan.course_id
     *
     * @mbg.generated Wed Sep 25 22:13:22 GMT+08:00 2019
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_plan.course_id
     *
     * @param courseId the value for course_plan.course_id
     *
     * @mbg.generated Wed Sep 25 22:13:22 GMT+08:00 2019
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_plan.num
     *
     * @return the value of course_plan.num
     *
     * @mbg.generated Wed Sep 25 22:13:22 GMT+08:00 2019
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_plan.num
     *
     * @param num the value for course_plan.num
     *
     * @mbg.generated Wed Sep 25 22:13:22 GMT+08:00 2019
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_plan.school_time
     *
     * @return the value of course_plan.school_time
     *
     * @mbg.generated Wed Sep 25 22:13:22 GMT+08:00 2019
     */
    public String getSchoolTime() {
        return schoolTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_plan.school_time
     *
     * @param schoolTime the value for course_plan.school_time
     *
     * @mbg.generated Wed Sep 25 22:13:22 GMT+08:00 2019
     */
    public void setSchoolTime(String schoolTime) {
        this.schoolTime = schoolTime == null ? null : schoolTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_plan.mark
     *
     * @return the value of course_plan.mark
     *
     * @mbg.generated Wed Sep 25 22:13:22 GMT+08:00 2019
     */
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_plan.mark
     *
     * @param mark the value for course_plan.mark
     *
     * @mbg.generated Wed Sep 25 22:13:22 GMT+08:00 2019
     */
    public void setMark(String mark) {
        this.mark = mark == null ? null : mark.trim();
    }
}