package com.lib.equipment.manager.model;

import java.util.Date;

public class OutStorage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_storage.id
     *
     * @mbg.generated Thu Sep 19 20:02:21 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_storage.out_time
     *
     * @mbg.generated Thu Sep 19 20:02:21 CST 2019
     */
    private Date outTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_storage.material_id
     *
     * @mbg.generated Thu Sep 19 20:02:21 CST 2019
     */
    private Long materialId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_storage.num
     *
     * @mbg.generated Thu Sep 19 20:02:21 CST 2019
     */
    private Integer num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_storage.remark
     *
     * @mbg.generated Thu Sep 19 20:02:21 CST 2019
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_storage.id
     *
     * @return the value of out_storage.id
     *
     * @mbg.generated Thu Sep 19 20:02:21 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_storage.id
     *
     * @param id the value for out_storage.id
     *
     * @mbg.generated Thu Sep 19 20:02:21 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_storage.out_time
     *
     * @return the value of out_storage.out_time
     *
     * @mbg.generated Thu Sep 19 20:02:21 CST 2019
     */
    public Date getOutTime() {
        return outTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_storage.out_time
     *
     * @param outTime the value for out_storage.out_time
     *
     * @mbg.generated Thu Sep 19 20:02:21 CST 2019
     */
    public void setOutTime(Date outTime) {
        this.outTime = outTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_storage.material_id
     *
     * @return the value of out_storage.material_id
     *
     * @mbg.generated Thu Sep 19 20:02:21 CST 2019
     */
    public Long getMaterialId() {
        return materialId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_storage.material_id
     *
     * @param materialId the value for out_storage.material_id
     *
     * @mbg.generated Thu Sep 19 20:02:21 CST 2019
     */
    public void setMaterialId(Long materialId) {
        this.materialId = materialId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_storage.num
     *
     * @return the value of out_storage.num
     *
     * @mbg.generated Thu Sep 19 20:02:21 CST 2019
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_storage.num
     *
     * @param num the value for out_storage.num
     *
     * @mbg.generated Thu Sep 19 20:02:21 CST 2019
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_storage.remark
     *
     * @return the value of out_storage.remark
     *
     * @mbg.generated Thu Sep 19 20:02:21 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_storage.remark
     *
     * @param remark the value for out_storage.remark
     *
     * @mbg.generated Thu Sep 19 20:02:21 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}