package com.lib.equipment.manager.model;

public class Storage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage.id
     *
<<<<<<< HEAD
     * @mbg.generated Sun Sep 22 17:08:49 CST 2019
=======
     * @mbg.generated Sun Sep 22 17:10:23 GMT+08:00 2019
>>>>>>> b2289f50f201778ac5fd00a8fe82278614dd8d4b
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage.material_id
     *
<<<<<<< HEAD
     * @mbg.generated Sun Sep 22 17:08:49 CST 2019
=======
     * @mbg.generated Sun Sep 22 17:10:23 GMT+08:00 2019
>>>>>>> b2289f50f201778ac5fd00a8fe82278614dd8d4b
     */
    private Long materialId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage.num
     *
<<<<<<< HEAD
     * @mbg.generated Sun Sep 22 17:08:49 CST 2019
=======
     * @mbg.generated Sun Sep 22 17:10:23 GMT+08:00 2019
>>>>>>> b2289f50f201778ac5fd00a8fe82278614dd8d4b
     */
    private Integer num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage.place
     *
<<<<<<< HEAD
     * @mbg.generated Sun Sep 22 17:08:49 CST 2019
=======
     * @mbg.generated Sun Sep 22 17:10:23 GMT+08:00 2019
>>>>>>> b2289f50f201778ac5fd00a8fe82278614dd8d4b
     */
    private String place;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage.id
     *
     * @return the value of storage.id
     *
<<<<<<< HEAD
     * @mbg.generated Sun Sep 22 17:08:49 CST 2019
=======
     * @mbg.generated Sun Sep 22 17:10:23 GMT+08:00 2019
>>>>>>> b2289f50f201778ac5fd00a8fe82278614dd8d4b
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage.id
     *
     * @param id the value for storage.id
     *
<<<<<<< HEAD
     * @mbg.generated Sun Sep 22 17:08:49 CST 2019
=======
     * @mbg.generated Sun Sep 22 17:10:23 GMT+08:00 2019
>>>>>>> b2289f50f201778ac5fd00a8fe82278614dd8d4b
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage.material_id
     *
     * @return the value of storage.material_id
     *
<<<<<<< HEAD
     * @mbg.generated Sun Sep 22 17:08:49 CST 2019
=======
     * @mbg.generated Sun Sep 22 17:10:23 GMT+08:00 2019
>>>>>>> b2289f50f201778ac5fd00a8fe82278614dd8d4b
     */
    public Long getMaterialId() {
        return materialId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage.material_id
     *
     * @param materialId the value for storage.material_id
     *
<<<<<<< HEAD
     * @mbg.generated Sun Sep 22 17:08:49 CST 2019
=======
     * @mbg.generated Sun Sep 22 17:10:23 GMT+08:00 2019
>>>>>>> b2289f50f201778ac5fd00a8fe82278614dd8d4b
     */
    public void setMaterialId(Long materialId) {
        this.materialId = materialId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage.num
     *
     * @return the value of storage.num
     *
<<<<<<< HEAD
     * @mbg.generated Sun Sep 22 17:08:49 CST 2019
=======
     * @mbg.generated Sun Sep 22 17:10:23 GMT+08:00 2019
>>>>>>> b2289f50f201778ac5fd00a8fe82278614dd8d4b
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage.num
     *
     * @param num the value for storage.num
     *
<<<<<<< HEAD
     * @mbg.generated Sun Sep 22 17:08:49 CST 2019
=======
     * @mbg.generated Sun Sep 22 17:10:23 GMT+08:00 2019
>>>>>>> b2289f50f201778ac5fd00a8fe82278614dd8d4b
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage.place
     *
     * @return the value of storage.place
     *
<<<<<<< HEAD
     * @mbg.generated Sun Sep 22 17:08:49 CST 2019
=======
     * @mbg.generated Sun Sep 22 17:10:23 GMT+08:00 2019
>>>>>>> b2289f50f201778ac5fd00a8fe82278614dd8d4b
     */
    public String getPlace() {
        return place;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage.place
     *
     * @param place the value for storage.place
     *
<<<<<<< HEAD
     * @mbg.generated Sun Sep 22 17:08:49 CST 2019
=======
     * @mbg.generated Sun Sep 22 17:10:23 GMT+08:00 2019
>>>>>>> b2289f50f201778ac5fd00a8fe82278614dd8d4b
     */
    public void setPlace(String place) {
        this.place = place == null ? null : place.trim();
    }
}