package com.lib.equipment.manager.model;

import lombok.Data;

@Data
public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbg.generated Sat Sep 07 09:15:14 CST 2019
     */
    private Integer id;

    private String username;


    private String password;

    private String phone;

    private Integer status;


}