package com.lib.equipment.manager.mapper;

import com.lib.equipment.manager.model.CourseMatrial;
import com.lib.equipment.manager.model.CourseMatrialExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface CourseMatrialMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_matrial
     *
     * @mbg.generated Sat Sep 07 09:15:14 CST 2019
     */
    long countByExample(CourseMatrialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_matrial
     *
     * @mbg.generated Sat Sep 07 09:15:14 CST 2019
     */
    int deleteByExample(CourseMatrialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_matrial
     *
     * @mbg.generated Sat Sep 07 09:15:14 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_matrial
     *
     * @mbg.generated Sat Sep 07 09:15:14 CST 2019
     */
    int insert(CourseMatrial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_matrial
     *
     * @mbg.generated Sat Sep 07 09:15:14 CST 2019
     */
    int insertSelective(CourseMatrial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_matrial
     *
     * @mbg.generated Sat Sep 07 09:15:14 CST 2019
     */
    List<CourseMatrial> selectByExampleWithRowbounds(CourseMatrialExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_matrial
     *
     * @mbg.generated Sat Sep 07 09:15:14 CST 2019
     */
    List<CourseMatrial> selectByExample(CourseMatrialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_matrial
     *
     * @mbg.generated Sat Sep 07 09:15:14 CST 2019
     */
    CourseMatrial selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_matrial
     *
     * @mbg.generated Sat Sep 07 09:15:14 CST 2019
     */
    int updateByExampleSelective(@Param("record") CourseMatrial record, @Param("example") CourseMatrialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_matrial
     *
     * @mbg.generated Sat Sep 07 09:15:14 CST 2019
     */
    int updateByExample(@Param("record") CourseMatrial record, @Param("example") CourseMatrialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_matrial
     *
     * @mbg.generated Sat Sep 07 09:15:14 CST 2019
     */
    int updateByPrimaryKeySelective(CourseMatrial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_matrial
     *
     * @mbg.generated Sat Sep 07 09:15:14 CST 2019
     */
    int updateByPrimaryKey(CourseMatrial record);
}