package com.lib.equipment.manager.mapper;

import com.lib.equipment.manager.model.CoursePlan;
import com.lib.equipment.manager.model.CoursePlanExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface CoursePlanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_plan
     *
     * @mbg.generated Sat Sep 07 09:15:14 CST 2019
     */
    long countByExample(CoursePlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_plan
     *
     * @mbg.generated Sat Sep 07 09:15:14 CST 2019
     */
    int deleteByExample(CoursePlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_plan
     *
     * @mbg.generated Sat Sep 07 09:15:14 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_plan
     *
     * @mbg.generated Sat Sep 07 09:15:14 CST 2019
     */
    int insert(CoursePlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_plan
     *
     * @mbg.generated Sat Sep 07 09:15:14 CST 2019
     */
    int insertSelective(CoursePlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_plan
     *
     * @mbg.generated Sat Sep 07 09:15:14 CST 2019
     */
    List<CoursePlan> selectByExampleWithRowbounds(CoursePlanExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_plan
     *
     * @mbg.generated Sat Sep 07 09:15:14 CST 2019
     */
    List<CoursePlan> selectByExample(CoursePlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_plan
     *
     * @mbg.generated Sat Sep 07 09:15:14 CST 2019
     */
    CoursePlan selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_plan
     *
     * @mbg.generated Sat Sep 07 09:15:14 CST 2019
     */
    int updateByExampleSelective(@Param("record") CoursePlan record, @Param("example") CoursePlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_plan
     *
     * @mbg.generated Sat Sep 07 09:15:14 CST 2019
     */
    int updateByExample(@Param("record") CoursePlan record, @Param("example") CoursePlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_plan
     *
     * @mbg.generated Sat Sep 07 09:15:14 CST 2019
     */
    int updateByPrimaryKeySelective(CoursePlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_plan
     *
     * @mbg.generated Sat Sep 07 09:15:14 CST 2019
     */
    int updateByPrimaryKey(CoursePlan record);
}