package com.lib.equipment.manager.mapper;

import com.lib.equipment.manager.model.Storage;
import com.lib.equipment.manager.model.StorageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface StorageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage
     *
     * @mbg.generated Sun Sep 22 17:08:49 CST 2019
     */
    long countByExample(StorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage
     *
     * @mbg.generated Sun Sep 22 17:08:49 CST 2019
     */
    int deleteByExample(StorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage
     *
     * @mbg.generated Sun Sep 22 17:08:49 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage
     *
     * @mbg.generated Sun Sep 22 17:08:49 CST 2019
     */
    int insert(Storage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage
     *
     * @mbg.generated Sun Sep 22 17:08:49 CST 2019
     */
    int insertSelective(Storage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage
     *
     * @mbg.generated Sun Sep 22 17:08:49 CST 2019
     */
    List<Storage> selectByExampleWithRowbounds(StorageExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage
     *
     * @mbg.generated Sun Sep 22 17:08:49 CST 2019
     */
    List<Storage> selectByExample(StorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage
     *
     * @mbg.generated Sun Sep 22 17:08:49 CST 2019
     */
    Storage selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage
     *
     * @mbg.generated Sun Sep 22 17:08:49 CST 2019
     */
    int updateByExampleSelective(@Param("record") Storage record, @Param("example") StorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage
     *
     * @mbg.generated Sun Sep 22 17:08:49 CST 2019
     */
    int updateByExample(@Param("record") Storage record, @Param("example") StorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage
     *
     * @mbg.generated Sun Sep 22 17:08:49 CST 2019
     */
    int updateByPrimaryKeySelective(Storage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storage
     *
     * @mbg.generated Sun Sep 22 17:08:49 CST 2019
     */
    int updateByPrimaryKey(Storage record);
}